spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/planner_todo
    username: fin
    password: fin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: planner-todo
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro, rabbit
  cloud:
    function:
      definition: newUserActionConsume
    stream:
      bindings:
        newUserActionConsume-in-0:
          destination: planner-dest
          group: planner-group