spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fin
    username: fin
    password: fin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: planner-users
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro, rabbit
  cloud:
    function:
      definition: newUserActionProduce;orderProduce;orderReadyConsume
    stream:
      bindings:
        newUserActionProduce-out-0:
          destination: planner-dest
        orderProduce-out-0:
          destination: planner-order
          group: order
        orderReadyConsume-in-0:
          destination: planner-order-ready
          group: order

