spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fin
    username: fin
    password: fin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: planner-users
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro, rabbit
  cloud:
    function:
      definition: newUserActionProduce;orderUserSideProduce;wsOrdersUserSideProduce;orderReadyUserSideConsume;wsOrdersUserSideConsume;wsAdvOrdersUserSideConsume
    stream:
      bindings:
        newUserActionProduce-out-0:
          destination: planner-dest
        orderUserSideProduce-out-0:
          destination: planner-order
          group: order
          error-handler-definition: myErrorHandler
        wsOrdersUserSideProduce-out-0:
          destination: planner-ws-order
          group: order
          error-handler-definition: myErrorHandler
        orderReadyUserSideConsume-in-0:
          destination: planner-order-ready
          group: order
          error-handler-definition: myErrorHandler
        wsOrdersUserSideConsume-in-0:
          destination: planner-ws-order-ready
          group: order1
          error-handler-definition: myErrorHandler
        wsAdvOrdersUserSideConsume-in-0:
          destination: planner-ws-order-ready
          group: order2
          error-handler-definition: myErrorHandler





