spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fin
    username: fin
    password: fin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: indian-ps
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: indian-ps
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: net.pay.indianps.serialization.IndTransferDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: net.pay.indianps.serialization.IndTransferSerializer
