create table if not exists users
(
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    varchar(25) not null
);

create table categories
(
    category varchar(25) primary key
);

create table orders
(
    id       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  int references users (user_id),
    category varchar(25),
    constraint fk_users foreign key (user_id) references users (user_id)
);

create table orders_categories (
    order_id int,
    category varchar(25),
    primary key (order_id, category),
    constraint fk_order foreign key (order_id) references orders(id),
    constraint fk_categories foreign key (category) references categories(category)
)